services:
  db:
    image: mariadb:11.4
    restart: always
    environment:
      MYSQL_DATABASE: httpdb
      MYSQL_USER: httpdb
      MYSQL_PASSWORD: httpdb
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: mysql://httpdb:httpdb@db:3306/httpdb
      TZ: Asia/Shanghai
    ports:
      - "7090:7090"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7090/v1/get/test_json"]
      interval: 60s
      timeout: 10s
      retries: 3
    tty: true

volumes:
  db_data:
